// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWhiskyShelf.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MyWhiskyShelf.Migrations.Migrations
{
    [DbContext(typeof(MyWhiskyShelfDbContext))]
    [Migration("20251005210345_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyWhiskyShelf.Infrastructure.Persistence.Entities.DistilleryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Vector>("FlavourVector")
                        .IsRequired()
                        .HasColumnType("vector(5)")
                        .HasColumnName("FlavourVector");

                    b.Property<int>("Founded")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TastingNotes")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("FlavourVector")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FlavourVector"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FlavourVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Distilleries_Name_eq");

                    b.HasIndex("Owner");

                    b.HasIndex("Region");

                    b.HasIndex("Type");

                    b.ToTable("Distilleries");
                });

            modelBuilder.Entity("MyWhiskyShelf.Infrastructure.Persistence.Entities.WhiskyBottleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AbvPercentage")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<bool?>("AddedColouring")
                        .HasColumnType("boolean");

                    b.Property<int?>("BatchNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Bottler")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CaskNumber")
                        .HasColumnType("integer");

                    b.Property<bool?>("ChillFiltered")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DistilleryId")
                        .HasColumnType("uuid");

                    b.Property<string>("DistilleryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Vector>("FlavourVector")
                        .IsRequired()
                        .HasColumnType("vector(5)")
                        .HasColumnName("FlavourVector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<int>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("integer");

                    b.Property<int>("VolumeCl")
                        .HasColumnType("integer");

                    b.Property<int>("VolumeRemainingCl")
                        .HasColumnType("integer");

                    b.Property<int?>("YearBottled")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DistilleryName");

                    b.HasIndex("FlavourVector")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FlavourVector"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FlavourVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_WhiskyBottles_Name_eq");

                    b.HasIndex("Status");

                    b.ToTable("WhiskyBottles");
                });
#pragma warning restore 612, 618
        }
    }
}
