name: .NET testing
permissions:
  contents: none

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      project:
        required: true
        type: string
    
jobs:
  dotnet-tests:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
    
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
    
      - name: Restore Dependencies
        env:
          INPUT_PROJECT: ${{ inputs.project }}
        run: dotnet restore $INPUT_PROJECT
        
      - name: Update Aspire
        run: |
          dotnet workload config --update-mode manifests
          dotnet workload update
          dotnet new install Aspire.ProjectTemplates
    
      - name: Build solution
        env:
          INPUT_PROJECT: ${{ inputs.project }}
        run: dotnet build $INPUT_PROJECT --configuration Release --no-restore
    
      - name: Setup Dev Credentials
        run: dotnet dev-certs https --trust
        if: ${{ inputs.name == 'Integration' }}

      - name: Run tests
        env:
          INPUT_PROJECT: ${{ inputs.project }}
        run: |
          dotnet test  $INPUT_PROJECT \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            --configuration Release \
            --no-build \
            --verbosity normal
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        env:
          INPUT_NAME: ${{ inputs.name }}
        with:
          name: test-results-${{ env.INPUT_NAME }}
          path: ./TestResults
          overwrite: true